apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:BJX2bSRdJUc=,iv:2+WtUoCeuJyzU3PKt4Y1Lrvk5adm5l72ZVSOx1OId9s=,tag:TSEMSp6OCQdIV3kqp7zBxA==,type:str]
  CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:+Al7pukZ+qoYZFumrquba3++p86WoYTDp6oy9bfUkalexO9SYvAzYshunUPv4jCm7eSnE0g=,iv:M2pctC2unudt7WbdkKvZ+g6tjJZkxP2gpF8a/rnz8LU=,tag:B/g9+3BXrXiqydRNEwqQeg==,type:str]
  CLUSTER_API_ADDR: ENC[AES256_GCM,data:ngD/xkJEOj8=,iv:/MP8wnfad5XcN5XxlcJgTbTsse0PH2iz5+1chtcVKJw=,tag:xbI/RwmMZrFX64NbGfn7Hw==,type:str]
  CLUSTER_GATEWAY_ADDR: ENC[AES256_GCM,data:zpRhCEaGaT8=,iv:rRt3bbvIonrbEJjFsByI7covN07vfzIs/zikhwfOOT8=,tag:/yxT77ueSPalAaSjpdt8dA==,type:str]
  CLUSTER_DNS_GATEWAY_ADDR: ENC[AES256_GCM,data:ZjAaYMEeFWI=,iv:C3KxwH2TWo1Nyz8w8vcC+6Mqfh5rRkEDy5JQB7l1gWE=,tag:A8RDblm5QWKi5sTCLnkIqw==,type:str]
  NAS_SERVER: ENC[AES256_GCM,data:2bGn9x4RxrnA,iv:4jU+YJA92+GELG2txIBypOAtryFSJ88lqnQ/bWO3fSY=,tag:AMnRcmJ0/PHTXsiH4YPK8Q==,type:str]
  NAS_PATH: ENC[AES256_GCM,data:odcM2TvEAev9wakYN8nOYrumrg==,iv:xGKhAhP7dD5ReEA1BJIY1OOFkTl4lpPHK2quWjNEbTc=,tag:FaLtmYWQvJwymw7nNvIWfA==,type:str]
  NAS_CODING_PATH: ENC[AES256_GCM,data:+3YnLeQkotFP4g0p34f6,iv:UYy67SSZVl2hGVd3tb093ps0UGvKh5A/o2xBvZWqOHc=,tag:2Bo/veS12d2xHQBV9Vw++A==,type:str]
  TTYD_CREDENTIAL: ENC[AES256_GCM,data:uFXaq8V6k9tWE1qvddsO,iv:Nh6aMs5AsEXVkd0BdUTwOKg2jEl9py1bqO1evjYltr4=,tag:0vNnp30+rZRr3bSBLn/S4g==,type:str]
  FLUX_SYNC_URL: ENC[AES256_GCM,data:/Nc+3aOCwyvRn03fRk5EPRqAKmfILTIDZ0UVDGBp1nXWBne1,iv:Qoe4bGGxIyaLvfJ35RJKQZa2D0tAw7WMY/fk1P3qXw0=,tag:jgvWm+uMNsjBCwyfqd8FZQ==,type:str]
  CLOUDFLARE_TUNNEL_TOKEN: ENC[AES256_GCM,data:el4j1+r/ZHuPv4mjy/8pexGkwP/044yffsMrYI2f+ntVs6EwBdT7elTluJLF9o4AxE5SaW0sKufkKVmpk9mgQIVeGG2vOEEHBmPB66b1FklyTO5FocyNhZla9Ufw8Yw/Ty59HPWhRJYy1SW5ZBeUZlfaFb7aHfAzjxp5dgA+5/2ogoyCSuZHOYFaaC6f10Oq2w+Uu4kcsAMan1q6+B5uegrs1g0KKqtEXSUTNxXsyn0Tc8wN5ms4zBtrvvz+UwCpdxgytnOuqgDa5wUyaN4m8S0DWCCn1yGcQxHbKPUwurjPy8MfeIzlCTmb7d66gzKW5xUWFR0C3h4=,iv:pnBicg1RpmHpoDl4BgE61/W7lspGPuWr77CmJu6FpCU=,tag:y4vVnQdRIp5gN/GbMjc5BA==,type:str]
  GITHUB_WEBHOOK_TOKEN: ENC[AES256_GCM,data:eYgnIzgKX5qdwcHx5JnJMH/znDD8V/9VKgJ6MdkYYrhY0V5F0YtFzrCjTzHaitSYvz2ia+HC3DDfPFPLe6kXmehh2dmKPQ==,iv:rkyl+erMFkixJvA5b+f4hM0R2dU8IRUHuU+piVzBWFk=,tag:51EV3XwpOlvhwfFW1hIQvQ==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:KLM8QCCPKG4FcTY=,iv:ZvqNAOvhEYq4zq43616zByxUtEp7IuHcqp8GRoiu8iE=,tag:3M6LcwCzyhRsmw0hxJSKOA==,type:str]
  TRELLO_API_KEY: ENC[AES256_GCM,data:JKt3UVYmHKACIuPJPwXg8hTqMQ3w3BmYoVgKJ1tMBKU=,iv:boRcUxexEmZJqWp84KzecTxm9+gTWSJ/xdrPfQjNQuw=,tag:/wIBkUXTuf4Wfpxrg4seyA==,type:str]
  TRELLO_API_TOKEN: ENC[AES256_GCM,data:HkI8cACBhs63ufZEyGz1mFH6PGlCwzmyEbw2/1bkWKZ41j6McQczn0+NmNXGGujrUsUDNG21bhj3MZQ3gv/Wi0pHrdjJoOs+4ozFUw==,iv:wyZFsTZ6S08D8LM/kUloDJ/M1y+sqxxX1YAw3FuhiYE=,tag:ak8QBherxWhAl879MwVOdA==,type:str]
  TRELLO_BOARD_ID: ""
  LINE_CHANNEL_ACCESS_TOKEN: ENC[AES256_GCM,data:b1XdBNSxa9GmaMqKwYZzD5pSXSHJMmigcIR/mXL6IcvcyJHMF+TnqM8UcyuuF5yFj7C9ytOMU2c6rrBqvLnxnO9n7EBYBEH9ew1y9xTkXPUFlocTd5fYYQ/f5VbQuOlqwFvGQnm5hud5V5ggDfQ6UbFe2yh0siMXKWFkzLikAoq3N32I7hWsV3QFbApp1DILQuA1JIyGXRYM24njG9pTH/mHcLM8hUIZl7/QdQ==,iv:TVnE+UiV9xmzKT7TcuWW9O/G62Ao27lEZaxf0KVbrws=,tag:0hkL1p5E/QrSFZeDOW4fEw==,type:str]
  LINE_CHANNEL_SECRET: ENC[AES256_GCM,data:0LX5gSG65zwB0L5Q+hI6o8xDi0dG4MKnx3UjaNkeahg=,iv:ukgG2CPIDcnnzWIVTO6IZCYSP/HJ3AcTJjtZLcaaz+Y=,tag:LQmW0IN31n48RFSp0NBUQg==,type:str]
  LINE_NOTIFY_GROUP_ID: ""
  ANTHROPIC_API_KEY: ENC[AES256_GCM,data:gXQLpS5O7qTAGGD66Ne80IMeiVMAPhh3Av3ovfmHuS4hsQlbvR221ex+QDMgIen9n5InUDK50oLF/vCzhaxbeIGVXG+C4vZj/H751Nz8q/ybxgXaFJZZCQd8W7uMFfPLFh5wqv4c9ddBJF7I,iv:qrHlz4YT/a1Lx3owHwqHpEkLNLwbx95S0JUP++hk4gY=,tag:npS6x2MX96g1n0SsnuDTmQ==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:HjKcGmZlwdjGY4k05dinKnvAbrL5dTcsW4uuKeFQz6hqXLPqewlBb3RU5DoLPrTvkNmTpEzvfMo=,iv:tL2KZRJ5VrDw82L9f4M75Xe+4FUrItWU3YGku2l8Uts=,tag:u2z3WUaq5/3IVpxWOap/Hg==,type:str]
  SYNOPHOTO_AUTH0_DOMAIN: ENC[AES256_GCM,data:u+jMAIPKqnPmf+D+qBRtDYswqvgybgmoxzkaLi7CcGKq,iv:0ANQ9Fqu2iccUm/uKb2Nt4QA/IYqKK9G7irPw8uOguc=,tag:qtFarJbhdtwEG2j/2N9o+w==,type:str]
  SYNOPHOTO_AUTH0_CLIENT_ID: ENC[AES256_GCM,data:aZt0t/O8E/lKl0blVLRh00MYebhRkwdAovi9vxr1Er4=,iv:kMxVPI/jTN9dxhT6/8VcdWFpr2L0dT0KuY7oWmf0GG4=,tag:j70fSuogCZMJX5FVbsTvRA==,type:str]
  SYNOPHOTO_AUTH0_CLIENT_SECRET: ENC[AES256_GCM,data:d/B3Ffwc4KTVDPxNLLsQi2PvHWf+qeENYETrsWeTYMnjdh28Oo/hanw3N+hxA9uNN3YEilAPdJWqwLHHaQmxBg==,iv:2HeYosWbmVkLkTpcAQmDBeAR0GaRZBKrketacMOV82Y=,tag:1fC3MwdxZLjEnmACr8SC/A==,type:str]
  SYNOPHOTO_ALLOWED_EMAILS: ENC[AES256_GCM,data:TjmE+HApQT6Q1x3KLSOMsvf9,iv:UA8G7cYl5bx2eVIGSWFfO2TPtRHcGodCKRC0+/AecRk=,tag:cYRnoLZ8lAp6O+33aIZo5Q==,type:str]
  SYNOPHOTO_FLASK_SECRET_KEY: ENC[AES256_GCM,data:yP2ia+WnrKUEZOzG1KgFq+CAX7KDJtDSnFeDuC8ieYbv4MmVYv9uLZJK0HyldxZ6VRxtvHQMjPFBXYbrrqOBwA==,iv:6QMd0yHVroGd54m7XMHeZ0iFtDNM6QnPze9LWhKY4qs=,tag:LNSCY+3+7o+C2Pf/0idOCQ==,type:str]
sops:
  age:
    - recipient: age1adlqyg2lplhtr5g5chd9w45qal7rek4fu22pj6nryfhhsqmscsqq42qgzx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWGhKM0ZFcmZzMzBkN295
        NE4yK2xYM2w4SmZVV0svV3h4TVJOSmp4M21nCk5id1pqZGtyTkNTYlZLcVFRVDY2
        TmlRdlRmU2dKL2o0M2lyWkxOYTFjUHcKLS0tIEZjOW9wdUtqd2xZaXNxK3RHeEhN
        cFQrZjRrTGpWTk5MSzF3cDBMQUVLSjgKhVwaXho9S3jc+m+lZWgHfR6RSFZhsAI2
        LRBSXKzHO2hBRYFfrew2TFfXiFNC23OjHUsDG9P8TMbwmtwm/xDbfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-12T06:13:56Z"
  mac: ENC[AES256_GCM,data:12V59kNxUmj3KB77SBTPSdlUgPxELoxwEohmd7+CTYdiL6fJOGJCakWymls0k9HqCb77f34NpIEJmObs0jLcbFXNUpsA9xylG/yvHrmBeLf+BAPN2XgBPT0hRvkzZjYzIHNEMNSAWVju7y7HqaffkN0RPPMBGAV0q2eemBW3bjo=,iv:6SO8zj/kgk2i7K1yEcYLYXBBRwx4+Kgkkr4ER/dvEsA=,tag:r4vdjHNPg+2tNA70QMCRGA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
