apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:+xps7wVXQ50=,iv:mF7VWeppzfm1vnnkl7O8revIXwJAtnx/iYsNNUg9hQ8=,tag:9ayYPaosPLhNQum34KVLzQ==,type:str]
  CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:vN/suKYdnFEtIOkxaLdB8hu7hImKrvFizBkifLsP7O+/xxedO1N9i3gSk8243kyT33zQD30=,iv:+U9TScEKmdyCnTS4jnlsotxude9VCY3nVWnZziNG2jc=,tag:wTmRqaiz/Il63lpiM+W6rw==,type:str]
  CLUSTER_API_ADDR: ENC[AES256_GCM,data:HeocbZWblQM=,iv:R8x4wNb1ctmgDVieyp8NTDvZkSrWdE7ciYsZVuGsmVo=,tag:yaFuraMcUFDhOiUhSuOB6w==,type:str]
  CLUSTER_GATEWAY_ADDR: ENC[AES256_GCM,data:ipyw8lZWU0Y=,iv:bLQrSUMKyqWjrX4mONNoMHOMmPSoHyf/Bz4rT7vsWqY=,tag:YjuWfPeoTMpwmGCrsk5gRw==,type:str]
  CLUSTER_DNS_GATEWAY_ADDR: ENC[AES256_GCM,data:fnrXXXxoMaQ=,iv:pIeYGEKRDJJllE5XWaamG4R/kXV2O2JvmwmwCqeCpW8=,tag:FbEyCR0Qlt8Yc7+N3W5Iew==,type:str]
  NAS_SERVER: ENC[AES256_GCM,data:bH7R956uc0Cj,iv:dXpLgoENHDS3GM8+iJXUDB0snA3URmerE6/0yo+iexU=,tag:mGNPa1d/C9Cq/PDf5qGNaQ==,type:str]
  NAS_PATH: ENC[AES256_GCM,data:nlysrQWmi+Okpgh2sXdu+zwU1g==,iv:BB8X2gzQlmKBejYJ8aNo9nPWOb7Df27v/SYFk4HK7eQ=,tag:XzY12Er8auOdICXUlZpUrg==,type:str]
  NAS_CODING_PATH: ENC[AES256_GCM,data:Pq3e1KuUAuAP7novSIkc,iv:GN6DtmbZDeSvb3OgPYSCNbfawN+KJmK/0rofQOkG/tc=,tag:/jSkqBh1NXqe/BFhmWUYLA==,type:str]
  TTYD_CREDENTIAL: ENC[AES256_GCM,data:Q6GL4ACIEjsUvDTPMQcT,iv:JD5puBUrPC5tK94P47144ROARTN+Rl9+s+nA+bzIcSo=,tag:iWEF4fU4zEPz+o5c3CeXjw==,type:str]
  FLUX_SYNC_URL: ENC[AES256_GCM,data:Czw2vHw/Q2P28jSswHga1rvG/IajY8HRzk+ddmt+5a7SfUPX,iv:yu6+IogCAPhfgJs7dcUUuNyMlBGyDZD0JoGMRb+DAMQ=,tag:UsGrp5VlHMh0A/ofMVjwgA==,type:str]
  CLOUDFLARE_TUNNEL_TOKEN: ENC[AES256_GCM,data:5BAFQFUQ80Igk0P00OU6EMbBwqThzra7zojkIcGh49XdKFiL0YG78dTHeR9WmkacfuJKMp4/yUvc10OmyE5qZUP76n5VefctWT5mDIEKAFVsf9Rqjf/DVcoN30IXoC9Pw8ji9UJbZfDLwl9BgWzWJ5Ijo2OYfYj1l0xFl+DvxIGU0WJmDM2Ru10SuJ/idd/329mQhQ3g5+FYER/ui19ucN0GYVQ3ozHu1bhu0Hg2y6M/yOS5yF0U7euUvyQgkZuW1hThHlYCuNrgR5mD2n/ywqwpNKtrFDis0g+bLt2KHdRsrtPUp0wbUBfhnNNmgMOMcGwVLGFaHiE=,iv:7yb6578TUpjAxSIVFJGFH7CaxdV7TebNjXb2o0bRLbY=,tag:Ya/NwDrM9bFLz5fAd1zyeA==,type:str]
  GITHUB_WEBHOOK_TOKEN: ENC[AES256_GCM,data:0rF0bJ2EGyPUcfLxvUTyO6NmrvP0QbfNVgFktNInN+y4Fe2yhQ80Gt+kRjtm//yci+ES1AiEExJl+ww1au8E2qLgjvqb5g==,iv:L1r5rUe8vdfiYl6y/2cio+eu2pB/SydESLGQDvG5ASE=,tag:UwCra/bFUvfAQ7K1yPizjQ==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:FdMguCxbK+xO3b8=,iv:s09HkQK2iF+dOdy9vbc3EN12JP5ruKAL4wcHCYV9Vjw=,tag:rwRPQVCcRj5v4SVV8pR37g==,type:str]
  TRELLO_API_KEY: ENC[AES256_GCM,data:ebGtBWxAu1zK6pLhuTWaHHLB98/7ON2k+gAOqm15kAg=,iv:gfKBreDr840nE2d7Jxsr8mxzb3x00HI6CmJ3y6pmBx4=,tag:doORko6PTABMJaKVTyxFVw==,type:str]
  TRELLO_API_TOKEN: ENC[AES256_GCM,data:VD0qFSm3pXlrs9j5VBqcBzWW8sNE8nSuGHtTLDl/Ct3cTbpAKO9VtHjorTi7sP2Co53115op7KZEmRg1gP+GG1a/+VG5JAn7/nOt0Q==,iv:a4uQnUDIrBHY8MoFFGZIhfoKAP3WSsEeZ9qm0z69Zp0=,tag:VqFNvJuALDrNadaHxySwCA==,type:str]
  TRELLO_BOARD_ID: ""
  LINE_CHANNEL_ACCESS_TOKEN: ENC[AES256_GCM,data:Gt8o1BWUh312DFbP1XpOzugTnuK+BkmU5MUDRg/2OO4esIrOg55v8uh91ex+tzFKN9bleMqNNctKB/oO3gcVHjMjIrS80zoAhCEpdRxiMLgc66IJPVStAK63cvA488wY3yp4eM2DDFQ4uiybZo/+D3u0NH09py9RUqKIMybHUcguUNks2JjdjiONa7ZckLhSHbEOLjbyHGQImU5yEjMLmkm1usNYvVrd14xsoA==,iv:/kVznvRibIrlfjIZq3ikDwOO5sGhMajA73Tija5O+1w=,tag:pmrn0s2Sydh/LBjtYzDnCQ==,type:str]
  LINE_CHANNEL_SECRET: ENC[AES256_GCM,data:VvL6iLH1oY+4gVw/RVieJVqDKXg80suffRrwDZNBJLk=,iv:h8QxCNiY5U8leYfjABfCLmqhVKjQruJN6buDmkVmVSg=,tag:1bTRSRU0/0uEj5+hSexDcw==,type:str]
  LINE_NOTIFY_GROUP_ID: ""
  ANTHROPIC_API_KEY: ENC[AES256_GCM,data:e8yDa3j55EyV4KthFgSwE5DOQCtI9Fvg59ASOVGxWzVEqZYQZvrkQ/mCoL7PLvAktylYvlAXWDZR3DCpJInePJbr6xoY3ufHFKnfjiOVTtN9Y7MqUaqspZ1qjmKT1U8iKb7dMXnJHK4tgvG9,iv:gU0XWDMCdv8CDGgvk7PDWxtbDQt8X9uDAtljczu0KiM=,tag:lkO5GzAkMAcjOm6b2yavhg==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:XOV6VnUV6kU7SyblPBuQBq49X9z9bfBoPR0c4CkhO1APgk/pozo0/DFawqJ2WbV2LkNxwrU1DAY=,iv:8QGyTz6Fu1CRZKXIIUaddH1atMMCLqDO3TSDlzzdgR8=,tag:JrRqKJzFqAm0CClib37Pmg==,type:str]
sops:
  age:
    - recipient: age1adlqyg2lplhtr5g5chd9w45qal7rek4fu22pj6nryfhhsqmscsqq42qgzx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1c3FnenJGVkNBUktlU2Vu
        Rmw5NkpWOWROdkZmeE5PZFRNYStqSjBzeWpBCmxWVHAzR09SK3FRS3YycTQ3b2w5
        K0gzODNVUHBEcXdtNTJFU3EvaU5EcDQKLS0tIDM3ZFAxVjNkalJRU0tJc29Fdzhn
        dnRDQWxHdWUrMkFqLzAyUXBQSDBjK2sKDXN4IZhE1LZ528eB0rrsTckbwjtbr+xC
        j3FbZVVHJzKnc/iPnPioiG9BTX7gj47DS4fHY/GA8gGHeXFZ9STm1Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T15:12:31Z"
  mac: ENC[AES256_GCM,data:SHBXRzP7lLHD2qBvTrTCC9IXj2sXWkKSRCfgLaFAIXpekFG8YNmUHZA/m+fmsp/Ld10IfKmpCuZiTBXXP97uVVlEQgAoIRN3v2t+vmDGmokA4UiYmm4+SM+JmsevvaHphNMviJXzXCVJmhZysKmfdyBEfs+ka/yImOmCL2zGoa0=,iv:Ywe3/DjWcV7LTfAytdBodCDO8467VnMbL8eeWLWhegU=,tag:/+EdzyGgKm34YQ+n3x/oQQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
