apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:xRyNG/LsxNU=,iv:Ifyfgs6cALK8Rbx2R+Q/cdArmVvVhGGCgzN/1VzS7fs=,tag:QszWN1zeQvF11+B38Ez/2A==,type:str]
  CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:feqDtYwfh47BT2hD/o37tDV/pc/2RTJ6VFkDUosq/u+ynhqlBcr3jtv6H6oP+AFM8Nw/wpM=,iv:pcgvhvTHQ64Iw0t61EJ95pd64dAkWh5cvqQ2QYaLAZA=,tag:gLotXe4AhVOh7sDWxYzvSg==,type:str]
  CLUSTER_API_ADDR: ENC[AES256_GCM,data:58pQuZZoXIk=,iv:+F2myUZJ8NKeBW7uq0AP9iAdLtrNfFLO1XBxLqE8A3c=,tag:GBoqHigKwiOblOh3wl94XA==,type:str]
  CLUSTER_GATEWAY_ADDR: ENC[AES256_GCM,data:OBjLsUUr1dE=,iv:xdmzl75jmC38YNpexAZenwW6jtlj51P6yxOopjVvlp8=,tag:0c6s2mVMdrBvyI3VcHD27Q==,type:str]
  CLUSTER_DNS_GATEWAY_ADDR: ENC[AES256_GCM,data:/z1eGGC2tVg=,iv:sNxVCUIuqmigNEkHyyvAFukAyN/9XuNOJjMescwu4y8=,tag:+Qf11MLhzO1BjHGeFOP3UQ==,type:str]
  NAS_SERVER: ENC[AES256_GCM,data:0YFN52FM4Ytu,iv:W9gyagMMyRW1YgrpJt1F+d7l3TAR1ow6vH7umAT2H10=,tag:H2Qk1pVlULSd/ALTIPg5pg==,type:str]
  NAS_PATH: ENC[AES256_GCM,data:CrK4dPGWQlLOiwiQabSSiihwDA==,iv:Bkfkv8alI9hB7iwowrEUEC8WHphmsPRVJTKjKhN89lU=,tag:KIkLzJ0Zq8beKWRJHfK2pQ==,type:str]
  NAS_CODING_PATH: ENC[AES256_GCM,data:NvTr7vnJvPPU04Dfummt,iv:NHUJjxZgZDjqGYe8zf+myQMvs9c+VFhxqp0Z1jN86TI=,tag:Af9aGMzdoDxPrS1Uc7aNgA==,type:str]
  TTYD_CREDENTIAL: ENC[AES256_GCM,data:4lNh3qVlDxIluFK4h0K5,iv:WvVgkrvO3AOlP0Xo3EwqoFO5D/hKXA9MP0ePaqIOwjI=,tag:sfDnHZYYsCDoA3yRojflsg==,type:str]
  FLUX_SYNC_URL: ENC[AES256_GCM,data:Ru+esWDOOaelWyn7qLpaqaYXar8PVB6JtEU0tDjr7rUxGfBr,iv:wJqANC2quIATsHKwSK1BwRhOxTLFdwLkI66iKgCk0+Q=,tag:aQesltDvC7K3LxaTBpTjVw==,type:str]
  CLOUDFLARE_TUNNEL_TOKEN: ENC[AES256_GCM,data:IHW9aotyJH7tfLw6ITYIRpKbWZ6c1/irPuM3f8etovkhr12/0DsnXv0e6NoggYQ/aJ13yDNxRHAI7YNFj6qgapKKh8YViuHvWmqjSBGaxZxy5WL8MxaRrqtzlTF0YonmySEWW4ZeXANYEBcuMMyGlajtt430RM+jHtrcX2HRHffxNOpv/ONeZOr1tqbrQ/Jep2ITdRWElcrXgv/gPcew1S80gzbPB0vqgGJaRiO+MF/v8Y1SM88HfDcgbZT2YqkcO+nILkRen2ztbgWdDPm9ePHZgaiHgKb8ZfHDqwIHRVQlLnhjFjoqAzyBAo4cTyYUy7RMFWxBvRQ=,iv:+mglQLFXlJqn2Bj9Dq5kL3+SMHWbvoGkZyurSLHuePM=,tag:QBuiXLiyHJHYK33MthXD7g==,type:str]
  GITHUB_WEBHOOK_TOKEN: ENC[AES256_GCM,data:lA70/m3jaAF4awf6Is5jyDNBrA3tjCTx7kfARTgoPc5I8YzR7+Z6r3xTYnYuFlMYv3olTyqHTghXvYbpwdgx/SMnBORbBw==,iv:yqCaKXVwjinhxlSNmCyRS/qvIQ26TLrQEB5XxWOYUVQ=,tag:uWEu9f680yWah5siSrcTEg==,type:str]
  TRELLO_API_KEY: ""
  TRELLO_API_TOKEN: ""
  TRELLO_BOARD_ID: ""
  LINE_CHANNEL_ACCESS_TOKEN: ""
  LINE_NOTIFY_GROUP_ID: ""
sops:
  age:
    - recipient: age1adlqyg2lplhtr5g5chd9w45qal7rek4fu22pj6nryfhhsqmscsqq42qgzx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWWZMSlpsUEttMURZcWUv
        WGk1MFlnOVJBTXJkT2dQWnJOSXlJYXY4VFMwCkVaSXozNlRoUXNYcWRCaEVIVldL
        RzRpd2tBbWNzdWFnK2FSSXZlcUkxY00KLS0tIGhpU2Z5R1A5a1o4N0swNlIwaWFt
        VHNuR1VUNitvVlRFOUlFbGtRYkk1K00KL3sdkj9HLgmrqLgNNZXx4KcQn3hV+rYO
        7UkaQjfcKddY4/utwl/IRHj3xnB3VV00F8zQ7oTNDZ/BzeIwG79eVw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-01T12:47:22Z"
  mac: ENC[AES256_GCM,data:3RFnpPgPHO8clJZk8T5OVYXZs7BLdlf7ErYY8a2e7WruUM4UEf7ZPUC0d2lyy3lPeuycrxMzJWAisAsf0pv0xrsq2Ak93k+ISuU8kEQm4zxY1NRV13K4r/XarNfkx26JRFzGihci+EaVmglNiAaZOre1jjJSuHqJdSCnxS5K/Ig=,iv:U8ciofpXXrTdwQ2vogDYhLmgT1OQIAurGtQ/4U3brm8=,tag:hnD5mCfEZV7tJyv6Q7RUqQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
